from eventsourcing.tests.example_application_tests.base import ExampleApplicationTestCase
from eventsourcing.tests.stored_event_repository_tests.base_cassandra import CassandraRepoTestCase


class TestExampleApplicationWithCassandra(CassandraRepoTestCase, ExampleApplicationTestCase):
    pass
