# Generated by Django 3.0.4 on 2020-04-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TimestampSequencedRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "sequence_id",
                    models.UUIDField(
                        help_text="Sequence ID (e.g. an entity or aggregate ID)."
                    ),
                ),
                (
                    "position",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=6,
                        help_text="Position (timestamp) of item in sequence.",
                        max_digits=24,
                    ),
                ),
                (
                    "topic",
                    models.TextField(
                        help_text="Topic of the item (e.g. path to domain event class)."
                    ),
                ),
                (
                    "state",
                    models.BinaryField(
                        help_text="State of the item (serialized dict, possibly encrypted)."
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("sequence_id", "position")},
            },
        ),
        migrations.CreateModel(
            name="StoredEventRecord",
            fields=[
                ("uid", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "application_name",
                    models.CharField(help_text="Application name.", max_length=32),
                ),
                (
                    "originator_id",
                    models.UUIDField(
                        help_text="Originator ID (e.g. an entity or aggregate ID)."
                    ),
                ),
                (
                    "originator_version",
                    models.BigIntegerField(
                        help_text="Originator version of item in sequence."
                    ),
                ),
                ("pipeline_id", models.IntegerField(help_text="Pipeline ID.")),
                (
                    "notification_id",
                    models.BigIntegerField(help_text="Notification ID."),
                ),
                (
                    "topic",
                    models.TextField(
                        help_text="Topic of the item (e.g. path to domain event class)."
                    ),
                ),
                (
                    "state",
                    models.BinaryField(
                        help_text="State of the item (serialized dict, possibly encrypted)."
                    ),
                ),
                (
                    "causal_dependencies",
                    models.TextField(help_text="Causal dependencies."),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {
                    ("application_name", "pipeline_id", "notification_id"),
                    ("application_name", "originator_id", "originator_version"),
                },
            },
        ),
        migrations.CreateModel(
            name="SnapshotRecord",
            fields=[
                ("uid", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "sequence_id",
                    models.UUIDField(
                        help_text="Sequence ID (e.g. an entity or aggregate ID)."
                    ),
                ),
                (
                    "position",
                    models.BigIntegerField(
                        help_text="Position (index) of item in sequence."
                    ),
                ),
                (
                    "topic",
                    models.TextField(
                        help_text="Topic of the item (e.g. path to domain event class)."
                    ),
                ),
                (
                    "state",
                    models.BinaryField(
                        help_text="State of the item (serialized dict, possibly encrypted)."
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("sequence_id", "position")},
            },
        ),
        migrations.CreateModel(
            name="NotificationTrackingRecord",
            fields=[
                (
                    "uid",
                    models.BigAutoField(
                        help_text="Position (timestamp) of item in sequence.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "application_name",
                    models.CharField(help_text="Application name.", max_length=32),
                ),
                (
                    "upstream_application_name",
                    models.CharField(
                        help_text="Upstream application name.", max_length=32
                    ),
                ),
                ("pipeline_id", models.IntegerField(help_text="Pipeline ID.")),
                (
                    "notification_id",
                    models.BigIntegerField(help_text="Notification ID."),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {
                    (
                        "application_name",
                        "upstream_application_name",
                        "pipeline_id",
                        "notification_id",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="IntegerSequencedRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "sequence_id",
                    models.UUIDField(
                        help_text="Sequence ID (e.g. an entity or aggregate ID)."
                    ),
                ),
                (
                    "position",
                    models.BigIntegerField(
                        help_text="Position (index) of item in sequence."
                    ),
                ),
                (
                    "topic",
                    models.TextField(
                        help_text="Topic of the item (e.g. path to domain event class)."
                    ),
                ),
                (
                    "state",
                    models.BinaryField(
                        help_text="State of the item (serialized dict, possibly encrypted)."
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("sequence_id", "position")},
            },
        ),
        migrations.CreateModel(
            name="EntitySnapshotRecord",
            fields=[
                ("uid", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "application_name",
                    models.CharField(help_text="Application name.", max_length=32),
                ),
                (
                    "originator_id",
                    models.UUIDField(
                        help_text="Originator ID (e.g. an entity or aggregate ID)."
                    ),
                ),
                (
                    "originator_version",
                    models.BigIntegerField(
                        help_text="Originator version of item in sequence."
                    ),
                ),
                (
                    "topic",
                    models.TextField(
                        help_text="Topic of the item (e.g. path to domain event class)."
                    ),
                ),
                (
                    "state",
                    models.BinaryField(
                        help_text="State of the item (serialized dict, possibly encrypted)."
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {
                    ("application_name", "originator_id", "originator_version")
                },
            },
        ),
    ]
