# To use this Docker file in PyCharm, just add a new Docker project interpreter,
# and set an image name such as "eventsourcing_requirements:latest". It will
# take a little while to download and build everything, but then tests which
# do not depend on other services such as MySQL and Cassandra should pass.
# To run containers needed to pass the full test suite, see docker-compose.yaml.
FROM python:3.7

WORKDIR /app

# Copy enough to install the eventsourcing requirements.
COPY setup.py /app/setup.py
RUN mkdir eventsourcing
COPY eventsourcing/__init__.py /app/eventsourcing/

# Install the requirements.
RUN pip install -e .[testing]

# Remove the package source files.
RUN pip uninstall eventsourcing --yes
RUN rm -rf /app/eventsourcing
