# To use this Docker Compose file in PyCharm, just add a new Docker Compose
# project interpreter, and pick "all_eventsourcing_requirements" as the service. It
# will take a little while to download and build everything, then all tests should pass.
# Please note, both MySQL and Cassandra containers need a little while to get started
# first time the containers are run, so connections might not work immediately.
version: '2'

services:
    eventsourcing_requirements:
        build:
            context: ..
            dockerfile: ./dev/Dockerfile_eventsourcing_requirements
        image: "eventsourcing_requirements:latest"
        volumes:
            - .:/app
        links:
            - service_cassandra
            - service_mysql
            - service_postgres
            - service_redis
        env_file:
          - .env

    service_cassandra:
        image: "cassandra:latest"
        ports:
            - "7000:7000"

    service_mysql:
        image: "mysql:latest"
        env_file:
            - .env
        ports:
            - "3306:3306"

    service_postgres:
        image: "postgres:latest"
        env_file:
          - .env
        ports:
            - "5432:5432"

    service_redis:
        image: "redis:latest"
