# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: processor.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='processor.proto',
  package='processor',
  syntax='proto3',
  serialized_options=b'\n\021io.grpc.processorB\016ProcessorProtoP\001\242\002\003HLW',
  serialized_pb=b'\n\x0fprocessor.proto\x12\tprocessor\"\x07\n\x05\x45mpty\"\'\n\x0bInitRequest\x12\x18\n\x10\x61pplication_name\x18\x01 \x01(\t\"@\n\rFollowRequest\x12\x15\n\rupstream_name\x18\x01 \x01(\t\x12\x18\n\x10upstream_address\x18\x02 \x01(\t\"B\n\x0bLeadRequest\x12\x17\n\x0f\x64ownstream_name\x18\x01 \x01(\t\x12\x1a\n\x12\x64ownstream_address\x18\x02 \x01(\t\"&\n\rPromptRequest\x12\x15\n\rupstream_name\x18\x01 \x01(\t\"*\n\x14NotificationsRequest\x12\x12\n\nsection_id\x18\x01 \x01(\t\"%\n\x12NotificationsReply\x12\x0f\n\x07section\x18\x01 \x01(\t\"@\n\x0b\x43\x61llRequest\x12\x13\n\x0bmethod_name\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x01(\t\x12\x0e\n\x06kwargs\x18\x03 \x01(\t\"\x19\n\tCallReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\xfc\x02\n\tProcessor\x12,\n\x04Ping\x12\x10.processor.Empty\x1a\x10.processor.Empty\"\x00\x12\x36\n\x06\x46ollow\x12\x18.processor.FollowRequest\x1a\x10.processor.Empty\"\x00\x12\x32\n\x04Lead\x12\x16.processor.LeadRequest\x1a\x10.processor.Empty\"\x00\x12\x36\n\x06Prompt\x12\x18.processor.PromptRequest\x1a\x10.processor.Empty\"\x00\x12T\n\x10GetNotifications\x12\x1f.processor.NotificationsRequest\x1a\x1d.processor.NotificationsReply\"\x00\x12G\n\x15\x43\x61llApplicationMethod\x12\x16.processor.CallRequest\x1a\x14.processor.CallReply\"\x00\x42+\n\x11io.grpc.processorB\x0eProcessorProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='processor.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=37,
)


_INITREQUEST = _descriptor.Descriptor(
  name='InitRequest',
  full_name='processor.InitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='application_name', full_name='processor.InitRequest.application_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=78,
)


_FOLLOWREQUEST = _descriptor.Descriptor(
  name='FollowRequest',
  full_name='processor.FollowRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='upstream_name', full_name='processor.FollowRequest.upstream_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upstream_address', full_name='processor.FollowRequest.upstream_address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=144,
)


_LEADREQUEST = _descriptor.Descriptor(
  name='LeadRequest',
  full_name='processor.LeadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='downstream_name', full_name='processor.LeadRequest.downstream_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='downstream_address', full_name='processor.LeadRequest.downstream_address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=212,
)


_PROMPTREQUEST = _descriptor.Descriptor(
  name='PromptRequest',
  full_name='processor.PromptRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='upstream_name', full_name='processor.PromptRequest.upstream_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=252,
)


_NOTIFICATIONSREQUEST = _descriptor.Descriptor(
  name='NotificationsRequest',
  full_name='processor.NotificationsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='section_id', full_name='processor.NotificationsRequest.section_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=296,
)


_NOTIFICATIONSREPLY = _descriptor.Descriptor(
  name='NotificationsReply',
  full_name='processor.NotificationsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='section', full_name='processor.NotificationsReply.section', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=335,
)


_CALLREQUEST = _descriptor.Descriptor(
  name='CallRequest',
  full_name='processor.CallRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='method_name', full_name='processor.CallRequest.method_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='processor.CallRequest.args', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kwargs', full_name='processor.CallRequest.kwargs', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=401,
)


_CALLREPLY = _descriptor.Descriptor(
  name='CallReply',
  full_name='processor.CallReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='processor.CallReply.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=428,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['InitRequest'] = _INITREQUEST
DESCRIPTOR.message_types_by_name['FollowRequest'] = _FOLLOWREQUEST
DESCRIPTOR.message_types_by_name['LeadRequest'] = _LEADREQUEST
DESCRIPTOR.message_types_by_name['PromptRequest'] = _PROMPTREQUEST
DESCRIPTOR.message_types_by_name['NotificationsRequest'] = _NOTIFICATIONSREQUEST
DESCRIPTOR.message_types_by_name['NotificationsReply'] = _NOTIFICATIONSREPLY
DESCRIPTOR.message_types_by_name['CallRequest'] = _CALLREQUEST
DESCRIPTOR.message_types_by_name['CallReply'] = _CALLREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'processor_pb2'
  # @@protoc_insertion_point(class_scope:processor.Empty)
  })
_sym_db.RegisterMessage(Empty)

InitRequest = _reflection.GeneratedProtocolMessageType('InitRequest', (_message.Message,), {
  'DESCRIPTOR' : _INITREQUEST,
  '__module__' : 'processor_pb2'
  # @@protoc_insertion_point(class_scope:processor.InitRequest)
  })
_sym_db.RegisterMessage(InitRequest)

FollowRequest = _reflection.GeneratedProtocolMessageType('FollowRequest', (_message.Message,), {
  'DESCRIPTOR' : _FOLLOWREQUEST,
  '__module__' : 'processor_pb2'
  # @@protoc_insertion_point(class_scope:processor.FollowRequest)
  })
_sym_db.RegisterMessage(FollowRequest)

LeadRequest = _reflection.GeneratedProtocolMessageType('LeadRequest', (_message.Message,), {
  'DESCRIPTOR' : _LEADREQUEST,
  '__module__' : 'processor_pb2'
  # @@protoc_insertion_point(class_scope:processor.LeadRequest)
  })
_sym_db.RegisterMessage(LeadRequest)

PromptRequest = _reflection.GeneratedProtocolMessageType('PromptRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROMPTREQUEST,
  '__module__' : 'processor_pb2'
  # @@protoc_insertion_point(class_scope:processor.PromptRequest)
  })
_sym_db.RegisterMessage(PromptRequest)

NotificationsRequest = _reflection.GeneratedProtocolMessageType('NotificationsRequest', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONSREQUEST,
  '__module__' : 'processor_pb2'
  # @@protoc_insertion_point(class_scope:processor.NotificationsRequest)
  })
_sym_db.RegisterMessage(NotificationsRequest)

NotificationsReply = _reflection.GeneratedProtocolMessageType('NotificationsReply', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONSREPLY,
  '__module__' : 'processor_pb2'
  # @@protoc_insertion_point(class_scope:processor.NotificationsReply)
  })
_sym_db.RegisterMessage(NotificationsReply)

CallRequest = _reflection.GeneratedProtocolMessageType('CallRequest', (_message.Message,), {
  'DESCRIPTOR' : _CALLREQUEST,
  '__module__' : 'processor_pb2'
  # @@protoc_insertion_point(class_scope:processor.CallRequest)
  })
_sym_db.RegisterMessage(CallRequest)

CallReply = _reflection.GeneratedProtocolMessageType('CallReply', (_message.Message,), {
  'DESCRIPTOR' : _CALLREPLY,
  '__module__' : 'processor_pb2'
  # @@protoc_insertion_point(class_scope:processor.CallReply)
  })
_sym_db.RegisterMessage(CallReply)


DESCRIPTOR._options = None

_PROCESSOR = _descriptor.ServiceDescriptor(
  name='Processor',
  full_name='processor.Processor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=431,
  serialized_end=811,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='processor.Processor.Ping',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Follow',
    full_name='processor.Processor.Follow',
    index=1,
    containing_service=None,
    input_type=_FOLLOWREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Lead',
    full_name='processor.Processor.Lead',
    index=2,
    containing_service=None,
    input_type=_LEADREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Prompt',
    full_name='processor.Processor.Prompt',
    index=3,
    containing_service=None,
    input_type=_PROMPTREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetNotifications',
    full_name='processor.Processor.GetNotifications',
    index=4,
    containing_service=None,
    input_type=_NOTIFICATIONSREQUEST,
    output_type=_NOTIFICATIONSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CallApplicationMethod',
    full_name='processor.Processor.CallApplicationMethod',
    index=5,
    containing_service=None,
    input_type=_CALLREQUEST,
    output_type=_CALLREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROCESSOR)

DESCRIPTOR.services_by_name['Processor'] = _PROCESSOR

# @@protoc_insertion_point(module_scope)
